Navbar
MohamedTaha91/Netflix-Clone pull request #1
Opened 2024-09-25 14:23 UTC by MohamedTaha91

- Added Test 
- Finished v1 of UI
- Added Lucide React

![Navbar complete](https://github.com/user-attachments/assets/79a1a88d-1163-483d-9d88-0b003a0e2b8f)

2024-10-01 12:04 UTC, FCartier commented on src/components/navbar/index.tsx
> +        <Link href={"#"}>Inicio</Link>
Why put the names in Spanish? Wouldn't it make more sense to put them in English to share your work better later on?

2024-10-01 12:19 UTC, MohamedTaha91 commented on src/components/navbar/index.tsx
> +        <Link href={"#"}>Inicio</Link>
we can do that no problem, it was get things moving for now, when the navbar is full functional links wise i will change the names to english
```suggestion
        <Link href={"#"}>Inicio</Link>
```

2024-10-01 12:40 UTC, MohamedTaha91 commented on src/components/navbar/index.tsx
> +        <Link href={"#"}>Inicio</Link>
good call! Done

2024-10-01 14:27 UTC, FCartier commented on src/components/navbar/index.tsx
> +        <Link href={"#"}>Inicio</Link>
You haven't pushed your changes to this branch. Are you planning to push them with your next PR?

2024-10-02 12:11 UTC, FCartier commented on src/components/navbar/index.tsx
> +        <Link href={"#"}>Browse by languages</Link>
Similar comment: lines 18 to 23 are almost identical. Let's apply the DRY concept ( Don't Repeat Yourself )

2024-10-02 12:12 UTC, FCartier requested changes
Let's apply DRY concept!

2024-10-07 13:56 UTC, merged